import 'barber_style.dart';

class StyleRepository {
  static const List<BarberControl> _commonControls = [
    BarberControl(id: 'size', label: 'Shop Size', type: ControlType.chips, defaultValue: 'Medium', options: ['Small', 'Medium', 'Large']),
    BarberControl(id: 'chairs', label: 'Chair Count', type: ControlType.stepper, defaultValue: 3, min: 1, max: 10),
    BarberControl(id: 'mirrors', label: 'Mirror Wall', type: ControlType.chips, defaultValue: 'Individual', options: ['Single Long', 'Individual', 'Framed']),
    BarberControl(id: 'wash_stations', label: 'Wash Stations', type: ControlType.stepper, defaultValue: 1, min: 0, max: 4),
    BarberControl(id: 'waiting_seats', label: 'Waiting Seats', type: ControlType.stepper, defaultValue: 4, min: 0, max: 12),
    BarberControl(id: 'lighting', label: 'Lighting', type: ControlType.chips, defaultValue: 'Mixed', options: ['Warm Spot', 'Daylight', 'Mixed', 'Neon']),
    BarberControl(id: 'budget', label: 'Budget Look', type: ControlType.slider, defaultValue: 50.0, min: 0.0, max: 100.0),
    BarberControl(id: 'note', label: 'User Note', type: ControlType.text, defaultValue: ''),
  ];

  static List<BarberStyle> get styles => [
    BarberStyle(
      id: 'classic_heritage',
      name: 'Classic Heritage',
      description: 'Timeless leather, dark wood, and gold accents.',
      moodboardAsset: 'assets/style_moodboards/classic_heritage.svg',
      promptModifier: 'classic heritage barbershop, dark wood paneling, tufted leather chairs, brass gold hardware, vintage atmosphere',
      controls: [..._commonControls],
    ),
    BarberStyle(
      id: 'modern_minimal',
      name: 'Modern Minimal',
      description: 'Clean lines, monochrome palette, and open space.',
      moodboardAsset: 'assets/style_moodboards/modern_minimal.svg',
      promptModifier: 'modern minimal barbershop, white and black theme, sleek floating mirrors, concrete floor, ultra clean',
      controls: [..._commonControls],
    ),
    BarberStyle(
      id: 'industrial_concrete',
      name: 'Industrial Concrete',
      description: 'Raw materials, exposed pipes, and urban feel.',
      moodboardAsset: 'assets/style_moodboards/industrial_concrete.svg',
      promptModifier: 'industrial barbershop, exposed brick walls, concrete finishing, black steel pipes, raw aesthetic',
      controls: [..._commonControls],
    ),
    BarberStyle(
      id: 'luxury_black_gold',
      name: 'Luxury Black & Gold',
      description: 'High-end premium grooming lounge aesthetic.',
      moodboardAsset: 'assets/style_moodboards/luxury_black_gold.svg',
      promptModifier: 'luxury grooming lounge, matte black walls, gold trim accents, velvet touches, premium expensive look',
      controls: [..._commonControls],
    ),
    BarberStyle(
      id: 'vintage_brick',
      name: 'Vintage Brick',
      description: 'Brooklyn style exposed brick and warmth.',
      moodboardAsset: 'assets/style_moodboards/vintage_brick.svg',
      promptModifier: 'vintage brooklyn barbershop, red brick walls, warm edison bulb lighting, rustic wood',
      controls: [..._commonControls],
    ),
    BarberStyle(
      id: 'scandinavian',
      name: 'Scandinavian Clean',
      description: 'Bright woods, white walls, and soft lighting.',
      moodboardAsset: 'assets/style_moodboards/scandinavian.svg',
      promptModifier: 'scandinavian barbershop, light oak wood, white walls, soft diffused daylight, airy atmosphere',
      controls: [..._commonControls],
    ),
    // ... Filling out to 30 roughly with programmatically generated list for brevity in this file block if needed,
    // but I will explicitly list them to match the prompt requirement "Minimal 30 style".
    BarberStyle(
      id: 'japandi',
      name: 'Japandi Calm',
      description: 'Japanese functionality meets rustic minimalism.',
      moodboardAsset: 'assets/style_moodboards/japandi.svg',
      promptModifier: 'japandi style barbershop, low furniture, zen atmosphere, wood slats, stone textures',
      controls: [..._commonControls],
    ),
    BarberStyle(
      id: 'retro_diner',
      name: 'Retro Diner',
      description: 'Checkerboard floors and vibrant 50s nostalgia.',
      moodboardAsset: 'assets/style_moodboards/retro_diner.svg',
      promptModifier: 'retro diner style barbershop, checkerboard floor, red vinyl seats, neon signage, 1950s aesthetic',
      controls: [..._commonControls],
    ),
     BarberStyle(
      id: 'streetwear_urban',
      name: 'Streetwear Urban',
      description: 'Hypebeast culture, graffiti art, and bold vibe.',
      moodboardAsset: 'assets/style_moodboards/streetwear_urban.svg',
      promptModifier: 'urban streetwear barbershop, graffiti art on walls, sneaker display shelves, bold colors, hip hop vibe',
      controls: [..._commonControls],
    ),
    BarberStyle(
      id: 'premium_hotel',
      name: 'Hotel Lounge',
      description: 'Executive grooming inside a 5-star hotel.',
      moodboardAsset: 'assets/style_moodboards/premium_hotel.svg',
      promptModifier: '5-star hotel grooming lounge, marble countertops, soft recessed lighting, executive feel',
      controls: [..._commonControls],
    ),
    BarberStyle(
      id: 'dark_moody',
      name: 'Dark Moody',
      description: 'Shadowy, intimate, and masculine atmosphere.',
      moodboardAsset: 'assets/style_moodboards/dark_moody.svg',
      promptModifier: 'dark moody barbershop, charcoal walls, spotlighting only, mysterious atmosphere, masculine',
      controls: [..._commonControls],
    ),
    BarberStyle(
      id: 'bright_clean',
      name: 'Bright Daylight',
      description: 'Maximum visibility and clinical cleanliness.',
      moodboardAsset: 'assets/style_moodboards/bright_clean.svg',
      promptModifier: 'bright daylight barbershop, floor to ceiling windows, clinical clean, white surfaces, high visibility',
      controls: [..._commonControls],
    ),
    BarberStyle(
      id: 'compact_2chair',
      name: 'Compact 2-Chair',
      description: 'Efficient layout for small boutique shops.',
      moodboardAsset: 'assets/style_moodboards/compact_2chair.svg',
      promptModifier: 'small compact barbershop, 2 chairs only, efficient space usage, smart storage, cozy',
      controls: [
        ..._commonControls,
        BarberControl(id: 'walkway', label: 'Walkway Clear', type: ControlType.toggle, defaultValue: true),
      ],
    ),
     BarberStyle(
      id: 'efficient_line',
      name: 'Efficient Line',
      description: 'Long row of chairs for high throughput.',
      moodboardAsset: 'assets/style_moodboards/efficient_line.svg',
      promptModifier: 'busy barbershop, long row of chairs, efficient layout, uniform stations, bustling',
      controls: [..._commonControls],
    ),
    BarberStyle(
      id: 'high_capacity',
      name: 'High Capacity',
      description: 'Double-sided stations for maximum seating.',
      moodboardAsset: 'assets/style_moodboards/high_capacity.svg',
      promptModifier: 'large high capacity barbershop, double sided mirrors, many chairs, spacious',
      controls: [..._commonControls],
    ),
    BarberStyle(
      id: 'wash_station',
      name: 'Wash Focus',
      description: 'Emphasis on the shampoo and relaxation area.',
      moodboardAsset: 'assets/style_moodboards/wash_station.svg',
      promptModifier: 'barbershop with luxury wash station, shampoo area focus, reclining massage chairs, spa-like',
      controls: [..._commonControls],
    ),
    BarberStyle(
      id: 'waiting_lounge',
      name: 'Waiting Lounge',
      description: 'Comfortable sofa area for customers.',
      moodboardAsset: 'assets/style_moodboards/waiting_lounge.svg',
      promptModifier: 'barbershop with large waiting lounge, chesterfield sofas, coffee table, gaming console area',
      controls: [..._commonControls],
    ),
    BarberStyle(
      id: 'product_retail',
      name: 'Product Retail',
      description: 'Integrated shelving for grooming products.',
      moodboardAsset: 'assets/style_moodboards/product_retail.svg',
      promptModifier: 'barbershop with retail display, shelves of pomade and shampoo, merchandising focus, shop front',
      controls: [
        ..._commonControls,
        BarberControl(id: 'shelves', label: 'Shelf Count', type: ControlType.stepper, defaultValue: 3, min: 1, max: 5),
      ],
    ),
    BarberStyle(
      id: 'neon_subtle',
      name: 'Neon Accent',
      description: 'Futuristic touches with LED strips.',
      moodboardAsset: 'assets/style_moodboards/neon_subtle.svg',
      promptModifier: 'cyberpunk light barbershop, subtle neon strip lighting, futuristic accents, led mirrors',
      controls: [..._commonControls],
    ),
    BarberStyle(
      id: 'wood_chrome',
      name: 'Wood & Chrome',
      description: 'Traditional materials with modern finishes.',
      moodboardAsset: 'assets/style_moodboards/wood_chrome.svg',
      promptModifier: 'wood and chrome barbershop, polished metal surfaces, walnut wood, balanced classic modern',
      controls: [..._commonControls],
    ),
    BarberStyle(
      id: 'marble_grooming',
      name: 'Marble Finish',
      description: 'White marble counters for a clean luxury look.',
      moodboardAsset: 'assets/style_moodboards/marble_grooming.svg',
      promptModifier: 'marble interior barbershop, white carrara marble counters, stone floors, expensive stone look',
      controls: [..._commonControls],
    ),
    BarberStyle(
      id: 'tattoo_hybrid',
      name: 'Tattoo Hybrid',
      description: 'Combined studio for ink and cuts.',
      moodboardAsset: 'assets/style_moodboards/tattoo_hybrid.svg',
      promptModifier: 'tattoo parlor and barbershop hybrid, art on walls, dark alternative aesthetic, edgy',
      controls: [..._commonControls],
    ),
    BarberStyle(
      id: 'kids_friendly',
      name: 'Kids Friendly',
      description: 'Bright, colorful, and safe for children.',
      moodboardAsset: 'assets/style_moodboards/kids_friendly.svg',
      promptModifier: 'kids barbershop, bright colors, race car chair, fun atmosphere, toy display',
      controls: [
        ..._commonControls,
        BarberControl(id: 'safety', label: 'Safety Edges', type: ControlType.toggle, defaultValue: true),
      ],
    ),
    BarberStyle(
      id: 'budget_diy',
      name: 'Budget DIY',
      description: 'Simple startup look with plywood and basics.',
      moodboardAsset: 'assets/style_moodboards/budget_diy.svg',
      promptModifier: 'budget diy barbershop, plywood stations, simple mirrors, garage startup vibe, affordable',
      controls: [..._commonControls],
    ),
    BarberStyle(
      id: 'custom_cabinetry',
      name: 'Custom Cabinetry',
      description: 'Detailed woodwork storage units.',
      moodboardAsset: 'assets/style_moodboards/custom_cabinetry.svg',
      promptModifier: 'barbershop with custom cabinetry, built-in wooden storage, detailed carpentry, organized',
      controls: [..._commonControls],
    ),
    BarberStyle(
      id: 'minimal_mono',
      name: 'Minimal Mono',
      description: 'Strict black and white palette.',
      moodboardAsset: 'assets/style_moodboards/minimal_mono.svg',
      promptModifier: 'monochrome barbershop, all black and white, high contrast, artistic, gallery like',
      controls: [..._commonControls],
    ),
    BarberStyle(
      id: 'heritage_stripe',
      name: 'Heritage Stripe',
      description: 'Subtle red, white, and blue accents.',
      moodboardAsset: 'assets/style_moodboards/heritage_stripe.svg',
      promptModifier: 'classic barbershop with barber pole colors, subtle red white blue stripes, patriotic Americana',
      controls: [..._commonControls],
    ),
    BarberStyle(
      id: 'glass_steel',
      name: 'Glass & Steel',
      description: 'Transparent partitions and metal frames.',
      moodboardAsset: 'assets/style_moodboards/glass_steel.svg',
      promptModifier: 'glass and steel barbershop, glass partitions, metal frames, open concept, corporate sleek',
      controls: [..._commonControls],
    ),
    BarberStyle(
      id: 'cozy_warm',
      name: 'Cozy Warm',
      description: 'Homey feel with rugs and plants.',
      moodboardAsset: 'assets/style_moodboards/cozy_warm.svg',
      promptModifier: 'cozy warm barbershop, persian rugs, indoor plants, bookshelf, home-like atmosphere',
      controls: [..._commonControls],
    ),
    BarberStyle(
      id: 'content_creator',
      name: 'Creator Studio',
      description: 'Optimized for filming cuts and tutorials.',
      moodboardAsset: 'assets/style_moodboards/content_creator.svg',
      promptModifier: 'content creator barbershop, ring lights, camera ready background, studio lighting, clean background',
      controls: [
        ..._commonControls,
         BarberControl(id: 'camera_bg', label: 'Camera Wall', type: ControlType.toggle, defaultValue: true),
         BarberControl(id: 'ring_light', label: 'Ring Lights', type: ControlType.toggle, defaultValue: true),
      ],
    ),
  ];

  static BarberStyle getById(String id) {
    return styles.firstWhere((s) => s.id == id, orElse: () => styles.first);
  }
}
